#pragma once
#include "Variable.h"

#include "NullObject.h"
#include "Array.h"
#include "ArrayTemplate.h"
#include "String_t.h"
#include "Struct.h"
#include "Tree.h"

#include "Void.h"
#include "Any.h"
#include "Bool.h"
#include "Byte.h"
#include "UByte.h"
#include "Int.h"
#include "UInt.h"
#include "Long.h"
#include "ULong.h"
#include "Double.h"

#include "LinkToVariable.h"
#include "StackElement.h"
#include "MethodVariable.h"
#include "NamedObject.h"
#include "VariablePath.h"
#include "ArrayIndex.h"
#include "GoToMethod.h"
